### ISSUE TITLE
A bit of explanation

### ISSUE THREAD

**Issue by damionx7** [DanWahlin/ES2015Samples#4]
How to learn from these samples? A little guide would be useful.

**Comment by DanWahlin** [comment]
Thanks for the suggestion. These samples are used in talks and classes I run. While I don't have any plans to add explanations into the repository itself at this point, there are a lot of ES6/ES2015 guides out there if you're interested. Here are a few that should help out:

http://exploringjs.com/es6.html
https://ponyfoo.com/books/practical-modern-javascript/chapters#toc
https://github.com/lukehoban/es6features
